### ISSUE TITLE
Fix profile pictures 

### ISSUE THREAD

**Issue by DenizYil** [DenizYil/BDSA-Big-Hero-6#53]

**Comment by BE-CH** [comment]
Måske vi bare skulle bruge sådan nogle generic billeder tbh. Eventuelt kan brugeren vælge mellem 3 billeder under "My Profile". De 3 billeder der kan vælges i mellem er nogen generic billeder vi har lagt ind

**Comment by DenizYil** [comment]
Kan vi godt - det er ikke svært at lade brugeren uploade deres eget billede though. Måske en blanding er begge? Udfordringen fra mit vedkommende er om vi kan få deres billede fra Microsoft.

**Comment by BE-CH** [comment]
Fixed in PR #70
