### ISSUE TITLE
Function fixes

### ISSUE THREAD

**Issue by BE-CH** [DenizYil/BDSA-Big-Hero-6#63]
**We need to fix the functions below**
- The ``RemoveUserFromProject`` method does not actually remove user. 
- ~~The ``MyProjects`` page needs to show the projects that the logged in user/supervisor has joined/created.~~
- The ``UpdateProject`` is very wonky. Should be fixed both back-end and front-end. Actually it gives error ``System.ArgumentNullException: Value cannot be null. (Parameter 'source')``
- ~~Add Client User Fetch to AuthLayout (https://stackoverflow.com/questions/65198814/how-to-pass-a-value-from-a-page-to-the-layout-in-blazor)~~
- Update tests for ``ProjectController``
- The ProjectRepository Update Method does not seem to save the changes.

**Comment by DenizYil** [comment]
Fix trying to render before auth has been registered

**Comment by DenizYil** [comment]
Fix min max

**Comment by DenizYil** [comment]
Don't forget to fix readallbyuser for non supervisors
